### ISSUE TITLE
TODO/FIXME Count 22

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-views#61]
- [ ] TODO: add config option for CSRF secret cookie name (defaults to `_csrf`)
       Commit: (24c7a0c) Error handling and route handling refactoring.
       File:  [lib/views.js:54](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/views.js#L54)
       David I. Lehn commented 8 months ago

  - [ ] TODO: check if this special case is still needed or can be improved
       Commit: (24c7a0c) Error handling and route handling refactoring.
       File:  [lib/views.js:23](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/views.js#L23)
       David I. Lehn commented 8 months ago

  - [ ] FIXME: log?
       Commit: (26de9ad) Simplify override scanning.
       File:  [lib/packages.js:262](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L262)
       David I. Lehn commented 8 months ago

  - [ ] FIXME: add optionalDependencies?
       Commit: (cb0098f) Remove manifest and browserDependencies support.
       File:  [lib/packages.js:245](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L245)
       David I. Lehn commented 8 months ago

  - [ ] FIXME: add peerDependencies? they should non-peer deps elsewhere.
       Commit: (cb0098f) Remove manifest and browserDependencies support.
       File:  [lib/packages.js:244](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L244)
       David I. Lehn commented 8 months ago

  - [ ] TODO: check version as well
       Commit: (0a80b58) Reorganize module and remove requirejs dependency.
       File:  [lib/packages.js:203](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L203)
       Dave Longley commented 3 years ago

  - [ ] FIXME: document the purpose and usage of these dependencies
       Commit: (0a80b58) Reorganize module and remove requirejs dependency.
       File:  [lib/packages.js:199](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L199)
       Dave Longley commented 3 years ago

  - [ ] TODO: remove `bedrock config`, if possible... potentially use `config`
       Commit: (0a80b58) Reorganize module and remove requirejs dependency.
       File:  [lib/packages.js:191](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L191)
       Dave Longley commented 3 years ago

  - [ ] TODO: potentially handle this with a new `bedrock.main` public API
       Commit: (e770272) Remove SystemJS and update config properties.
       File:  [lib/packages.js:108](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L108)
       David I. Lehn commented a year ago

  - [ ] TODO: potentially handle this with a new `bedrock.main` public API
       Commit: (0a80b58) Reorganize module and remove requirejs dependency.
       File:  [lib/packages.js:34](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/packages.js#L34)
       Dave Longley commented 3 years ago

  - [ ] FIXME: document this better:
       Commit: (abc0c6d) Refactoring and importAll update.
       File:  [lib/commands.js:125](https://github.com/digitalbazaar/bedrock-views/blob/master/lib/commands.js#L125)
       David I. Lehn commented a year ago

  - [ ] TODO: description of 'bedrock-views.optimize.run' event
       Commit: (f40b8ea) Update README.
       File:  [README.md:75](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L75)
       David I. Lehn commented 3 years ago

  - [ ] TODO: description of 'bedrock-views.cli.optimize.configure' event
       Commit: (f40b8ea) Update README.
       File:  [README.md:74](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L74)
       David I. Lehn commented 3 years ago

  - [ ] TODO: description of 'bedrock-views.cli.compile-less.configure' event
       Commit: (f40b8ea) Update README.
       File:  [README.md:73](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L73)
       David I. Lehn commented 3 years ago

  - [ ] TODO: description of `bedrock-views.add` event (possibly rename as well)
       Commit: (57597ed) Add TODOs.
       File:  [README.md:69](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L69)
       Dave Longley commented 5 years ago

  - [ ] TODO: description of `bedrock-views.vars.get` event
       Commit: (57597ed) Add TODOs.
       File:  [README.md:68](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L68)
       Dave Longley commented 5 years ago

  - [ ] TODO: general
       Commit: (57597ed) Add TODOs.
       File:  [README.md:67](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L67)
       Dave Longley commented 5 years ago

  - [ ] TODO: description of how to override vue templates
       Commit: (c7c8f48) Remove AngularJS support.
       File:  [README.md:59](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L59)
       David I. Lehn commented a year ago

  - [ ] TODO: description of `bedrock.config.views.vars`
       Commit: (57597ed) Add TODOs.
       File:  [README.md:58](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L58)
       Dave Longley commented 5 years ago

  - [ ] TODO: use 'bedrock-views.vars.get' event
       Commit: (57597ed) Add TODOs.
       File:  [README.md:45](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L45)
       Dave Longley commented 5 years ago

  - [ ] TODO: command line usage of optimize
       Commit: (3be3eff) Update boilerplate; add main description, some other section info.
       File:  [README.md:44](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L44)
       Dave Longley commented 5 years ago

  - [ ] TODO: command line usage of compile-less
       Commit: (3be3eff) Update boilerplate; add main description, some other section info.
       File:  [README.md:43](https://github.com/digitalbazaar/bedrock-views/blob/master/README.md#L43)
       Dave Longley commented 5 years ago

       TODO Count          17
       FIXME Count         5
       Oldest Comment      5 years ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: command line usage of optimize

**Comment by dlongley** [comment]
Closing as all TODOs / FIXME are now only in the README or have had other issues filed for them.
